---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install neovim
    package:
      name: 
        - neovim

  - name: Install oh-my-zsh
    shell:
      cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - name: Change shell
    user:
      name: tommymallis
      shell: /bin/zsh 
