---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
    - include: tasks/nvim-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/dotfiles-setup.yml
    - include: tasks/fonts-setup.yml
    - include: tasks/node-setup.yml
