  - name: Installing stow
    apt: name=stow
  - name: Cloning .dotfiles
    ansible.builtin.git:
      become_user: tommymallis
      repo: 'https://github.com/whoop-t/.dotfiles.git'
      dest: "~/.dotfiles"
  - name: Stow dotfiles
    become_user: tommymallis
    shell: cd ~/.dotfiles && stow .
