  - name: Remove file (delete file)
    file:
      path: /usr/local/bin/nvim
      state: absent
  - name: Remove AstroNvim
    file:
      path: ~/.config/nvim
      state: absent
  - name: Install neovim appimage
    shell: curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
  - name: Give permissions to nvim
    file:
      path: ./nvim.appimage
      owner: root
      group: root
      mode: '0755'
  - name: move nvim appimage to bin
    become: true
    shell: mv ./nvim.appimage /usr/local/bin/nvim
  - name: Install AstroNvim
    become_user: tommymallis
    git:
      repo: 'https://github.com/AstroNvim/AstroNvim'
      dest: '~/.config/nvim'
